import { useState } from 'react'
import { Home, Users, Newspaper, UserRound, MapPin, Wallet, Bell, Search, Heart, MessageCircle, Share2, CarFront, Bike, BusFront, ChevronLeft, ArrowRight, Store, Compass, X } from 'lucide-react'
import './styles.css'

type Tab = 'Home' | 'Friend' | 'Feed' | 'Me'
const cityImage = 'https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=1200&q=85'
const cities = [
  { name: 'Lagos', country: 'Nigeria', image: 'https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=900&q=85', desc: 'Coastal energy, business and nightlife' },
  { name: 'Abuja', country: 'Nigeria', image: 'https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?auto=format&fit=crop&w=900&q=85', desc: 'Green spaces and wide boulevards' },
  { name: 'Tokyo', country: 'Japan', image: 'https://images.unsplash.com/photo-1540959733332-eab4deaccf18?auto=format&fit=crop&w=900&q=85', desc: 'Bright streets and hidden districts' },
]
const rides = [
  { name: 'City Cruiser', type: 'Car', price: '₦18,000', icon: 'car' },
  { name: 'Street Bike', type: 'Motorcycle', price: '₦6,500', icon: 'bike' },
  { name: 'City Van', type: 'Van', price: '₦12,000', icon: 'van' },
  { name: 'Lagos Napep', type: 'Napep', price: '₦3,000', icon: 'van' },
  { name: 'Road Bicycle', type: 'Bicycle', price: '₦1,200', icon: 'bike' },
]
function App() {
  const [tab, setTab] = useState<Tab>('Home')
  const [insideCity, setInsideCity] = useState(false)
  const [city, setCity] = useState('Lagos')
  const [liked, setLiked] = useState(false)
  const [query, setQuery] = useState('')
  const [notice, setNotice] = useState('')
  const enterCity = (name = city) => { setCity(name); setInsideCity(true); setTab('Home'); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  const notify = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(''), 2600) }
  const nav = [{ label: 'Home' as Tab, Icon: Home }, { label: 'Friend' as Tab, Icon: Users }, { label: 'Feed' as Tab, Icon: Newspaper }, { label: 'Me' as Tab, Icon: UserRound }]
  return <div className="worldplay-app">
    <header className="top-header"><button className="brand" onClick={() => { setTab('Home'); setInsideCity(false) }}><span className="brand-mark">W</span><span>World<span className="brand-accent">Play</span><small>YOUR WORLD, YOUR STORY</small></span></button><div className="header-actions"><span className="wallet"><Wallet size={16}/><b>₦25,000</b></span><button className="icon-button" aria-label="Notifications" onClick={() => notify('You are all caught up.')}><Bell size={20}/></button></div></header>
    {tab === 'Home' && !insideCity && <main className="page-content">
      <section className="hero-card" style={{ backgroundImage: `linear-gradient(90deg,rgba(7,13,27,.92),rgba(7,13,27,.3)),url(${cityImage})` }}><div className="hero-label"><span className="live-dot"/> YOUR NEXT ADVENTURE</div><h1>Build your life.<br/><span>Own the city.</span></h1><p>Explore vibrant places, meet friends and make your own story in a living world.</p><button className="primary-button" onClick={() => enterCity('Lagos')}>Enter City <ArrowRight size={17}/></button><div className="hero-location"><MapPin size={15}/> Lagos, Nigeria <span>•</span> 28°C</div></section>
      <section className="stats-row"><div className="stat-card"><span>PLAYER LEVEL</span><strong>01</strong><small>New explorer</small></div><div className="stat-card"><span>YOUR WALLET</span><strong>₦25k</strong><small>Available balance</small></div><div className="stat-card"><span>FRIENDS</span><strong>12</strong><small>Keep in touch</small></div></section>
      <section className="section-block"><div className="section-heading"><div><span className="eyebrow">FIND YOUR NEXT STOP</span><h2>Explore cities</h2></div><button className="text-button" onClick={() => notify('More cities are coming soon.')}>View all <ArrowRight size={15}/></button></div><div className="city-grid">{cities.map((c) => <article className="city-card" key={c.name}><img src={c.image} alt={`${c.name} city`} loading="lazy"/><div className="city-shade"/><div className="city-card-content"><span className="country-pill">{c.country}</span><h3>{c.name}</h3><p>{c.desc}</p><button className="small-button" onClick={() => enterCity(c.name)}>Explore City <ArrowRight size={14}/></button></div></article>)}</div></section>
      <section className="section-block"><div className="section-heading"><div><span className="eyebrow">GET AROUND</span><h2>Popular rides</h2></div><button className="text-button" onClick={() => notify('Vehicle marketplace is coming next.')}>See all <ArrowRight size={15}/></button></div><div className="ride-grid">{rides.slice(0,4).map(r => <article className="ride-card" key={r.name}><div className="ride-art">{r.icon === 'car' ? <CarFront size={38}/> : r.icon === 'bike' ? <Bike size={38}/> : <BusFront size={38}/>}</div><div><h3>{r.name}</h3><p>{r.type}</p><strong>{r.price}</strong></div></article>)}</div></section>
      <section className="community-banner"><div><span className="eyebrow">BETTER TOGETHER</span><h2>Your people are out there.</h2><p>Find friends and share moments from your world.</p></div><button className="primary-button" onClick={() => setTab('Friend')}>Find friends <ArrowRight size={16}/></button></section>
    </main>}
    {tab === 'Home' && insideCity && <main className="page-content city-page"><button className="back-button" onClick={() => setInsideCity(false)}><ChevronLeft size={18}/> Back to Home</button><section className="city-hero" style={{ backgroundImage: `linear-gradient(0deg,rgba(7,13,27,.94),rgba(7,13,27,.05)),url(${cities.find(c => c.name === city)?.image || cityImage})` }}><span className="country-pill">{cities.find(c => c.name === city)?.country || 'WorldPlay'}</span><h1>{city}</h1><p>Welcome to your city. Your next chapter starts here.</p><div className="city-weather"><span>28°C</span><span>•</span><span>City is active</span></div></section><section className="section-block"><div className="section-heading"><div><span className="eyebrow">YOUR CITY</span><h2>What would you like to do?</h2></div></div><div className="action-grid"><button onClick={() => notify('City map will be added in the next stage.')}><MapPin/><b>Explore map</b><small>Discover places</small></button><button onClick={() => notify('Shops are coming in the next stage.')}><Store/><b>Shops</b><small>Browse the market</small></button><button onClick={() => notify('Vehicle driving will be added in a later stage.')}><CarFront/><b>Vehicles</b><small>Choose your ride</small></button><button onClick={() => setTab('Friend')}><Users/><b>Meet people</b><small>Find city friends</small></button></div></section><section className="section-block"><div className="section-heading"><div><span className="eyebrow">DISCOVER</span><h2>City landmarks</h2></div></div><div className="landmark-grid">{cities.map(c => <button className="landmark-card" key={c.name} onClick={() => { setCity(c.name); notify(`${c.name} selected`) }}><img src={c.image} alt={c.name}/><span><b>{c.name} district</b><small>Explore this area</small></span><ArrowRight size={16}/></button>)}</div></section></main>}
    {tab === 'Friend' && <main className="page-content"><section className="simple-heading"><span className="eyebrow">YOUR COMMUNITY</span><h1>Friends</h1><p>Meet people and grow your circle.</p></section><label className="search-box"><Search size={18}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search friends"/></label><div className="people-list">{['Amara Okafor','Tunde Bello','Zainab Musa','David James','Aisha Ibrahim','Chidi Nwosu'].filter(n => n.toLowerCase().includes(query.toLowerCase())).map((n,i)=><div className="person-row" key={n}><div className={`avatar avatar-${i%6}`}>{n.split(' ').map(s=>s[0]).join('')}</div><div className="person-info"><b>{n}</b><small>{i%2 ? 'Active recently' : 'WorldPlay member'}</small></div><button className="outline-button" onClick={() => notify(`Friend request sent to ${n}.`)}>Add friend</button></div>)}</div></main>}
    {tab === 'Feed' && <main className="page-content"><section className="simple-heading"><span className="eyebrow">WHAT'S HAPPENING</span><h1>Community Feed</h1><p>Moments and stories from your world.</p></section><div className="post-composer"><div className="avatar avatar-0">YU</div><button onClick={() => notify('Post creation will be added in the next stage.')}>Share something with the community...</button></div><article className="feed-post"><div className="post-author"><div className="avatar avatar-2">AM</div><div><b>Amara Okafor</b><small>Lagos · 12 min ago</small></div></div><p>Beautiful evening in the city. Where should I explore next?</p><img className="post-image" src="https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=1000&q=85" alt="City skyline at dusk"/><div className="post-actions"><button onClick={() => setLiked(!liked)} className={liked ? 'liked' : ''}><Heart size={18} fill={liked ? 'currentColor' : 'none'}/> {liked ? 'Liked' : 'Like'}</button><button onClick={() => notify('Comments will be added in the next stage.')}><MessageCircle size={18}/> Comment</button><button onClick={() => notify('Share feature will be added in the next stage.')}><Share2 size={18}/> Share</button></div></article></main>}
    {tab === 'Me' && <main className="page-content"><section className="profile-hero"><div className="profile-avatar">YU</div><h1>Your Profile</h1><p>WorldPlay explorer · Level 1</p><span className="profile-balance"><Wallet size={17}/> ₦25,000 balance</span></section><div className="profile-menu"><button onClick={() => notify('Edit profile will be added in the next stage.')}><UserRound/> Edit profile <ArrowRight/></button><button onClick={() => notify('Your vehicle collection will be added in a later stage.')}><CarFront/> My vehicles <ArrowRight/></button><button onClick={() => notify('Settings will be added in the next stage.')}><Compass/> Settings <ArrowRight/></button></div></main>}
    {notice && <div className="toast" role="status">{notice}<button onClick={() => setNotice('')} aria-label="Close"><X size={14}/></button></div>}
    <nav className="bottom-nav" aria-label="Main navigation">{nav.map(({label,Icon})=><button key={label} className={tab === label ? 'nav-item active' : 'nav-item'} onClick={() => { setTab(label); if(label !== 'Home') setInsideCity(false); window.scrollTo({top:0,behavior:'smooth'}) }}><Icon size={21} strokeWidth={tab === label ? 2.5 : 1.8}/><span>{label}</span></button>)}</nav>
  </div>
}
export default App
